print("Operator + ", 25+5)
print("Operator - ", 25-5)
print("Operator * ", 25*5)
print("Operator / ", 25/5)
print("Operator % ", 15%6)
print("Operator // ", 25//5)
print("Operator ** ", 3**2)
print("Operator ** ", 3**3)
